global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ordersense-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8081'  # order-service
          - 'host.docker.internal:8082'  # rider-service
          - 'host.docker.internal:8083'  # restaurant-service
          - 'host.docker.internal:8084'  # payment-service
          - 'host.docker.internal:8085'  # action-executor
